#! /bin/sh

/bin/mount -a

echo "
            _ _ _ _ _ _ _ _ _ _ _ _
            \  _  _   _  _ _ ___
            / /__/ \ |_/
           / __   /  -  _ ___
          / /  / /  / /
  _ _ _ _/ /  /  \_/  \_ ______
___________\___\__________________
"
for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ] ;
	then
		echo "[RCS]: $initscript"
		$initscript
	fi
done
mount -t tmpfs tmpfs /tmp
mount -t jffs2 /dev/mtdblock3  /app
mount -t jffs2 /dev/mtdblock1  /config
if [ $? == 0 ]; then
        echo "mount app successful!"
fi 
telnetd & 
/app/app.sh&
